MvcTest/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcTest.Controllers
{
    public class AboutController : BaseController
    {
        // GET: About
        public ActionResult Info()
        {
            return View();
        }


        public ActionResult Help()
        {
            return View();
        }
    }
}

MvcTest/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcTest.Controllers
{
    public class ProfileController : BaseController
    {
        public ProfileController()
        {
            LogedRequirement = true;
        }


        //
        // GET: Profile/Index
        public ActionResult Index()
        {
            return RouteTo();
        }


    }
}

MvcTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                 @Html.Raw(MvcTest.Common.PartialViewHelper.LoggedAs());

                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Info", "Info", "About")</li>
                        <li>@Html.ActionLink("Pomoc", "Help", "About")</li>
                        <li>@Html.ActionLink("Pliki", "Index", "Uploads")</li>
                        <li>@Html.ActionLink("Mój profil", "Index", "Profile")</li>

                        @{ 
                            if (MvcTest.Common.PartialViewHelper.isLogged())
                            {
                                @Html.ActionLink("Wyloguj się", "Logout", "Home");
                            }
                            else
                            {
                                @Html.ActionLink("Zaloguj się", "Login", "Home");
                            }
                        }
                    </ul>
                </div>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>